DELETE FROM tours;
DELETE FROM units;
DELETE FROM floors;
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_2', 'Piso 2', 2, 'Piso', '/plants/floor_2.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_2_201', 'floor_2', '201', 'APARTMENT', NULL, NULL, 57.84, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_2_202', 'floor_2', '202', 'APARTMENT', NULL, NULL, 70.68, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_3', 'Piso 3', 3, 'Piso', '/plants/floor_3.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_3_301', 'floor_3', '301', 'APARTMENT', NULL, NULL, 57.84, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_3_302', 'floor_3', '302', 'APARTMENT', NULL, NULL, 70.68, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_4', 'Piso 4', 4, 'Piso', '/plants/floor_4.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_4_401', 'floor_4', '401', 'APARTMENT', NULL, NULL, 57.84, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_4_402', 'floor_4', '402', 'APARTMENT', NULL, NULL, 70.68, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_5', 'Piso 5', 5, 'Piso', '/plants/floor_5.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_5_501', 'floor_5', '501', 'APARTMENT', NULL, NULL, 57.84, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_5_502', 'floor_5', '502', 'APARTMENT', NULL, NULL, 70.68, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_6', 'Piso 6', 6, 'Piso', '/plants/floor_6.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_6_601', 'floor_6', '601', 'APARTMENT', NULL, NULL, 57.84, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_6_602', 'floor_6', '602', 'APARTMENT', NULL, NULL, 70.68, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_7', 'Piso 7', 7, 'Piso', '/plants/floor_7.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_7_701', 'floor_7', '701', 'APARTMENT', NULL, NULL, 57.84, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_7_702', 'floor_7', '702', 'APARTMENT', NULL, NULL, 70.68, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_8', 'Piso 8', 8, 'Piso', '/plants/floor_8.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_8_801', 'floor_8', '801', 'APARTMENT', NULL, NULL, 91.14, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_8_802', 'floor_8', '802', 'APARTMENT', NULL, NULL, 108.37, NULL, 'AVAILABLE', NULL);
INSERT INTO floors (id, name, level, type, image_path) VALUES ('floor_1', 'Piso 1', 1, 'Piso', '/plants/floor_s.png');
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_101', 'floor_1', '101', 'STORAGE', NULL, NULL, 14.29, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_102', 'floor_1', '102', 'STORAGE', NULL, NULL, 14.58, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_103', 'floor_1', '103', 'STORAGE', NULL, NULL, 14.59, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_104', 'floor_1', '104', 'STORAGE', NULL, NULL, 13.66, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_105', 'floor_1', '105', 'STORAGE', NULL, NULL, 13.9, NULL, 'AVAILABLE', NULL);
INSERT INTO units (id, floor_id, identifier, type, bedrooms, bathrooms, area_sqm, coordinates, state, tour_url) VALUES ('unit_1_106', 'floor_1', '106', 'STORAGE', NULL, NULL, 1.48, NULL, 'AVAILABLE', NULL);
